version: "3.9"
services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true        # dev only (prod에선 반드시 활성화)
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports: ["9200:9200","9600:9600"]
    networks: ["app_net"]
    volumes:
      - os-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: os-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OPENSEARCH_SECURITY_ENABLED=false     # dev only
    ports: ["5601:5601"]
    depends_on: [opensearch]
    networks: ["app_net"]

volumes:
  os-data:

networks:
  app_net:
    name: app_net   # 앱 스택과 같은 네트워크 이름 사용
